### ISSUE TITLE
wireguard module not available

### ISSUE THREAD

**Issue by Shoadi** [anduril/jetpack-nixos#128]
Hello,

so another thing that I intend to do, is to get wireguard going. 

Relevant configuration.nix looks like this:

>       wireguard.interfaces = {
>         wg0 = {
>           ips = ["####"];
>           peers = [
>             {
>               allowedIPs = ["####"];
>               endpoint = "####";
>               presharedKey = "####";
>               publicKey = "####";
>             }
>           ];
>           privateKey = "####";
>         };
>       };
>     };

    
But built fails with: 

```
× wireguard-wg0 - WireGuard Tunnel - wg0
     Loaded: loaded (/etc/systemd/system/wireguard-wg0service; linked; preset: enabled)
     Active: failed (Result: exit-code) since #### ago
    Process: #### ExecStart=/nix/store/####-unit-script-wireguard-wg0-start/bin/wireguard-wg0-start (code=exited, status=2)
    Process: #### ExecStopPost=/nix/store/####-unit-script-wireguard-wg0-post-stop/bin/wireguard-wg0-post-stop (code=exited, status=1/FAILURE)
   Main PID: #### (code=exited, status=2)
         IP: 0B in, 0B out
        CPU: 18ms

NIX systemd[1]: Starting WireGuard Tunnel - wg0...
NIX wireguard-wg0-start[####]: modprobe: FATAL: Module wireguard not found in directory /run/booted-system/kernel-modules/lib/modules/5.10.104
NIX wireguard-wg0-start[####]: Error: Unknown device type.
NIX systemd[1]: wireguard-wg0.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
NIX wireguard-wg0-post-stop[####]: Cannot find device "wg0"
NIX systemd[1]: wireguard-wg0.service: Control process exited, code=exited, status=1/FAILURE
NIX systemd[1]: wireguard-wg0.service: Failed with result 'exit-code'.
NIX systemd[1]: Failed to start WireGuard Tunnel - wg0.
```
`/run/booted-system/kernel-modules/lib/modules/5.10.104` indeed does not contain any wireguard module - so I am wondering - how can I contribute so that this works?

Thanks and have a great day.

**Comment by jmbaur** [comment]
The kernel build in this repo uses the `tegra_defconfig` from oe4t/linux-tegra-5.10, which does not set CONFIG_WIREGUARD to "y" or "m". I think it would be best for this repo to stay focused on hardware enablement, but it should be fairly straight forward to add wireguard support with a nixos config like so:

```nix
{ lib, ... }: {
  boot.kernelPatches = [{
    name = "enable-wireguard";
    patch = null;
    extraStructuredConfig.WIREGUARD = lib.kernel.yes; # or lib.kernel.module
  }];
}
```
