### ISSUE TITLE
kernel: consider enabling `CONFIG_IP6_NF_MATCH_RPFILTER`

### ISSUE THREAD

**Issue by nagisa** [anduril/jetpack-nixos#25]
More recent versions of the nixpkgs will invoke both `iptables` and `ip6tables` with `-m rpfilter` parameter. The first works, but the second command fails (thus failing to set up the firewall fully). Upon some spelunking it seems like the it might be up to the fact that `CONFIG_IP_NF_MATCH_RPFILTER=m` but `CONFIG_IP6_NF_MATCH_RPFILTER` is not set. Similar discrepancy can be observed for most other netfilters too. That said, I just went the route of disabling IPv6 for the system, so I can’t confirm if enabling this specific module is the minimal change necessary to make things work.

**Comment by danielfullmer** [comment]
Fixed by #28
